/**
 * A single billable "turn" extracted from a coding-agent log file.
 *
 * In the Claude Code JSONL format, each assistant-authored line represents
 * one model response and carries the token accounting for the prompt that
 * produced it (input/cache tokens) plus the tokens it generated (output
 * tokens). One UsageEvent = one such line.
 */
export interface UsageEvent {
  /** Which parser produced this event, e.g. "claude-code-jsonl". */
  format: string;
  /** Absolute path to the source log file this event came from. */
  sourceFile: string;
  /** Session identifier from the log, if present. */
  sessionId?: string;
  /** ISO-8601 timestamp of the assistant response. */
  timestamp: string;
  /**
   * Stable grouping key for "project" - derived from the log file's
   * containing directory (Claude Code organizes session logs one directory
   * per project). Use this for aggregation.
   */
  projectKey: string;
  /**
   * Human-friendly project label - the real working-directory path (`cwd`)
   * seen in the log, when available; falls back to `projectKey`.
   */
  projectDisplay: string;
  /** Model identifier string as recorded in the log, e.g. "claude-sonnet-5". */
  model: string;
  /** Fresh (non-cached) prompt tokens billed at the base input rate. */
  inputTokens: number;
  /** Prompt tokens written into the 5-minute prompt cache this turn. */
  cacheCreation5mTokens: number;
  /** Prompt tokens written into the 1-hour prompt cache this turn. */
  cacheCreation1hTokens: number;
  /** Prompt tokens served from the prompt cache this turn (discounted). */
  cacheReadTokens: number;
  /** Tokens generated by the model this turn. */
  outputTokens: number;
  /**
   * false when every token count above came from the log's own usage
   * metadata (exact, as billed by the API). true when the log line did not
   * expose usage metadata and the counts were derived from a chars/4
   * heuristic instead - always surfaced to the user, never silently exact.
   */
  estimated: boolean;
}

export interface TranscriptParser {
  /** Stable id for this parser, e.g. "claude-code-jsonl". */
  id: string;
  /** Human-readable label for reports/logs. */
  label: string;
  /** Cheap sniff test: does this file look like this parser's format? */
  sniff(sampleLines: string[]): boolean;
  /** Parse one file's raw text content into zero or more usage events. */
  parse(rawContent: string, filePath: string, projectKey: string, projectDisplayHint?: string): UsageEvent[];
}
